GET http://localhost:3000/subscribers



###


GET http://localhost:3000/subscribers/60808b55b80109f6b120f13c

###

POST http://localhost:3000/subscribers

Content-Type: application/json

{
    "name": "Amazing Cake",
    "subscribedToChannel": "ME and Myself"
}

###

DELETE http://localhost:3000/subscribers/60808b55b80109f6b120f13c


/// Had issues with POST, I used Postman and curl to POST/PATCH